import { motion } from "framer-motion";
import React from "react";
import Head from "next/head";

import LoginHeader from "./LoginHeader";
import Sign from "./Sign";

type Props = {};

function MainSign({}: Props) {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Discord Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://firebasestorage.googleapis.com/v0/b/weaboobot.appspot.com/o/android-chrome-512x512.png?alt=media&token=ff2bb7f9-313a-4846-91d6-fc61237ce4a4"
        />
      </Head>
      <LoginHeader />
      <Sign />
    </motion.div>
  );
}

export default MainSign;
